---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "us.gcr.io/qp-qai-devops-2021-06/krishan/flask-new:latest"
          ports:
            - name: http
              containerPort: 80
...
